#!/usr/bin/env bash
# install nginx web server
sudo apt-get update -y
sudo apt-get install -y nginx
sudo chown -R "$USER":"$USER" /var/www/html/index.nginx-debian.html
sudo chmod u+x /var/www/html/index.nginx-debian.html 
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart

