#!/usr/bin/env bash
# Install nginx on web-01 server
if [ ! -x /usr/sbin/nginx ]; then
    sudo apt -y update
    sudo apt install -y --allow-downgrades nginx
    sudo ufw allow 'Nginx HTTP'
fi
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start
