#!/usr/bin/env bash
# replacing 4 and 8 in the list

i=1
while ((i <= 10)); do
	echo "Best School"
	if ((i == 4)); then
		echo "bad luck"
		elif ((i == 8)); then
			echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
